# Generated by Django 2.2.19 on 2021-03-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=255, verbose_name='書籍名')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='著者名')),
                ('publisher', models.CharField(blank=True, max_length=255, verbose_name='出版社')),
                ('year', models.IntegerField(blank=True, verbose_name='年')),
                ('page', models.IntegerField(blank=True, verbose_name='ページ数')),
            ],
        ),
    ]
