# Generated by Django 2.2.19 on 2021-03-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, verbose_name='タイトル')),
                ('site', models.CharField(blank=True, max_length=255, verbose_name='サイト')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('day', models.CharField(blank=True, max_length=50, verbose_name='閲覧日')),
                ('remarks_ref', models.TextField(blank=True, max_length=1000, verbose_name='備考')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='remarks',
            field=models.TextField(blank=True, max_length=1000, verbose_name='備考'),
        ),
    ]
