# Generated by Django 2.2.19 on 2021-03-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210301_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='page',
            field=models.CharField(blank=True, max_length=20, verbose_name='ページ数'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.CharField(blank=True, max_length=20, verbose_name='発行年'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='url',
            field=models.CharField(blank=True, max_length=500, verbose_name='URL'),
        ),
    ]
